```python
from locust import HttpUser, task, between, SequentialTaskSet
import random

class UserBehavior(SequentialTaskSet):
    def on_start(self):
        """Called when a Locust user starts executing this task sequence."""
        self.client.headers = {"Content-Type": "application/json"}
        self.user_email = f"locust_user_{random.randint(1, 100000)}@example.com"
        self.user_password = "locust_password123"
        self.access_token = None
        self.refresh_token = None
        self.register_and_login()

    def register_and_login(self):
        # Register (only once per user)
        register_data = {
            "username": self.user_email.split('@')[0],
            "email": self.user_email,
            "password": self.user_password
        }
        with self.client.post("/api/auth/register", json=register_data, catch_response=True) as response:
            if response.status_code == 201:
                response.success()
            elif response.status_code == 409 and "already exists" in response.text:
                response.success() # User already registered, treat as success for idempotency
            else:
                response.failure(f"Failed to register user: {response.text}")

        # Login
        login_data = {
            "email": self.user_email,
            "password": self.user_password
        }
        with self.client.post("/api/auth/login", json=login_data, catch_response=True) as response:
            if response.status_code == 200:
                self.access_token = response.json()["access_token"]
                self.refresh_token = response.json()["refresh_token"]
                response.success()
            else:
                response.failure(f"Failed to login user: {response.text}")

    @task(3) # Higher weight
    def view_all_posts(self):
        """Browse all posts as an authenticated user."""
        headers = {"Authorization": f"Bearer {self.access_token}"}
        self.client.get("/api/posts/", headers=headers, name="View All Posts")

    @task(2)
    def view_single_post(self):
        """View a specific, existing post."""
        headers = {"Authorization": f"Bearer {self.access_token}"}
        # In a real scenario, you'd get actual post IDs from `view_all_posts`
        # For simplicity, we'll assume a few common IDs from seed data or random.
        post_id = random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 
        self.client.get(f"/api/posts/{post_id}", headers=headers, name="View Single Post")

    @task(1) # Lower weight, as post creation is less frequent
    def create_post(self):
        """Create a new post."""
        if not self.access_token:
            self.register_and_login() # Ensure user is logged in
        headers = {"Authorization": f"Bearer {self.access_token}"}
        post_data = {
            "title": f"Locust Test Post {random.randint(1, 100000)}",
            "content": "This is content generated by a Locust test user. Lorem ipsum dolor sit amet, consectetur adipiscing elit."
        }
        with self.client.post("/api/posts/", json=post_data, headers=headers, catch_response=True) as response:
            if response.status_code in [201, 403]: # 403 for regular user, accept as a valid test
                response.success()
            else:
                response.failure(f"Failed to create post: {response.text}")

    @task
    def view_whoami(self):
        """View own user profile."""
        headers = {"Authorization": f"Bearer {self.access_token}"}
        self.client.get("/api/auth/whoami", headers=headers, name="Who Am I")

    # Optional: task for refreshing token, but usually happens less often.
    # @task
    # def refresh_token(self):
    #     if self.refresh_token:
    #         headers = {"Authorization": f"Bearer {self.refresh_token}"}
    #         with self.client.post("/api/auth/refresh", headers=headers, catch_response=True) as response:
    #             if response.status_code == 200:
    #                 self.access_token = response.json()["access_token"]
    #                 response.success()
    #             else:
    #                 response.failure(f"Failed to refresh token: {response.text}")


class WebsiteUser(HttpUser):
    wait_time = between(1, 5) # Users wait between 1 and 5 seconds between tasks
    host = "http://localhost:5000" # Replace with your app's host
    tasks = [UserBehavior]

```