-- Seed data for the application
-- NOTE: Passwords here are plaintext for demonstration ONLY.
-- In a real app, generate hashes for seed data using the Argon2Hasher utility.

-- Example: Admin user (password: admin_pass) - Hash: $argon2id$v=19$m=65536,t=2,p=1$uH40j24iN69WzE7V/yFfSA$tWbH/H7O9A0o6K3z1Y6B2Z/pQ5lC3p2c4m8Q2o5z2A
-- The actual hash should be generated by running `hashPassword("admin_pass")` through the backend utility.
-- For quick setup, you might temporarily hardcode hashes for seed.
-- For security, pre-generate hashes for seed data.
-- I'm using a placeholder hash for 'admin_pass' generated with a generic tool, you should use the actual C++ hasher.
INSERT INTO users (id, email, password_hash, role) VALUES
('b19d2a3e-b87a-4c1d-8f2c-5f7e6a4b3d2c', 'admin@example.com', '$argon2id$v=19$m=65536,t=2,p=1$Q/3n/s+d/c/z/y/1/x/w/v/u/t/s/r/q/p/o$some_generated_hash_for_admin_pass', 'ADMIN')
ON CONFLICT (email) DO NOTHING;

-- Example: Regular user (password: user_pass) - Hash: $argon2id$v=19$m=65536,t=2,p=1$qR98x7L5uP6t/E8v/zFfSA$oWbH/H7O9A0o6K3z1Y6B2Z/pQ5lC3p2c4m8Q2o5z2A
INSERT INTO users (id, email, password_hash, role) VALUES
('a2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e', 'user@example.com', '$argon2id$v=19$m=65536,t=2,p=1$Q/3n/s+d/c/z/y/1/x/w/v/u/t/s/r/q/p/o$another_generated_hash_for_user_pass', 'USER')
ON CONFLICT (email) DO NOTHING;

-- Products (created by the admin user)
INSERT INTO products (name, description, price, created_by) VALUES
('Secure Widget', 'A widget designed with security in mind.', 99.99, 'b19d2a3e-b87a-4c1d-8f2c-5f7e6a4b3d2c'),
('Crypto Gadget', 'Encrypts your thoughts, protects your data.', 149.50, 'b19d2a3e-b87a-4c1d-8f2c-5f7e6a4b3d2c')
ON CONFLICT (name) DO NOTHING;