```java
package com.tasks.taskmanagement.service;

import com.tasks.taskmanagement.dto.ProjectDTO;
import com.tasks.taskmanagement.entity.Project;
import com.tasks.taskmanagement.entity.User;
import com.tasks.taskmanagement.exception.ResourceNotFoundException;
import com.tasks.taskmanagement.exception.UnauthorizedException;
import com.tasks.taskmanagement.repository.ProjectRepository;
import com.tasks.taskmanagement.util.MapperUtil;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class ProjectService {

    private final ProjectRepository projectRepository;
    private final UserService userService;
    private final AuthService authService;
    private final MapperUtil mapperUtil;

    @Transactional
    @CacheEvict(value = "projects", allEntries = true) // Evict all projects cache on create
    public ProjectDTO createProject(ProjectDTO projectDTO) {
        log.info("Creating new project: {}", projectDTO.getName());
        User currentUser = authService.getCurrentAuthenticatedUser();

        Project project = mapperUtil.map(projectDTO, Project.class);
        project.setOwner(currentUser); // Set current authenticated user as owner
        project.setId(null); // Ensure ID is generated by JPA

        Project savedProject = projectRepository.save(project);
        log.info("Project '{}' created successfully by user '{}'.", savedProject.getName(), currentUser.getUsername());
        return mapperUtil.map(savedProject, ProjectDTO.class);
    }

    @Cacheable(value = "projects", key = "#id")
    public ProjectDTO getProjectById(UUID id) {
        log.info("Fetching project with ID: {}", id);
        Project project = projectRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Project not found with ID: " + id));
        return mapperUtil.map(project, ProjectDTO.class);
    }

    @Cacheable(value = "projects", key = "'all'")
    public List<ProjectDTO> getAllProjects() {
        log.info("Fetching all projects.");
        return projectRepository.findAll().stream()
                .map(project -> mapperUtil.map(project, ProjectDTO.class))
                .collect(Collectors.toList());
    }

    @Cacheable(value = "projects", key = "'byOwner:' + #ownerId")
    public List<ProjectDTO> getProjectsByOwner(UUID ownerId) {
        log.info("Fetching projects for owner ID: {}", ownerId);
        return projectRepository.findByOwnerId(ownerId).stream()
                .map(project -> mapperUtil.map(project, ProjectDTO.class))
                .collect(Collectors.toList());
    }

    @Transactional
    @CacheEvict(value = "projects", allEntries = true) // Evict all projects cache on update
    public ProjectDTO updateProject(UUID id, ProjectDTO projectDTO) {
        log.info("Updating project with ID: {}", id);
        Project existingProject = projectRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Project not found with ID: " + id));

        // Authorization check: Only owner or admin can update
        User currentUser = authService.getCurrentAuthenticatedUser();
        if (!existingProject.getOwner().getId().equals(currentUser.getId()) && currentUser.getRole() != User.Role.ADMIN) {
            throw new UnauthorizedException("You are not authorized to update this project.");
        }

        existingProject.setName(projectDTO.getName());
        existingProject.setDescription(projectDTO.getDescription());
        // owner_id cannot be changed via this method, use specific admin endpoint if needed

        Project updatedProject = projectRepository.save(existingProject);
        log.info("Project with ID {} updated successfully.", id);
        return mapperUtil.map(updatedProject, ProjectDTO.class);
    }

    @Transactional
    @CacheEvict(value = "projects", allEntries = true) // Evict all projects cache on delete
    public void deleteProject(UUID id) {
        log.info("Deleting project with ID: {}", id);
        Project existingProject = projectRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Project not found with ID: " + id));

        // Authorization check: Only owner or admin can delete
        User currentUser = authService.getCurrentAuthenticatedUser();
        if (!existingProject.getOwner().getId().equals(currentUser.getId()) && currentUser.getRole() != User.Role.ADMIN) {
            throw new UnauthorizedException("You are not authorized to delete this project.");
        }

        projectRepository.deleteById(id);
        log.info("Project with ID {} deleted successfully.", id);
    }

    // Helper method to retrieve Project entity
    public Project getProjectEntityById(UUID id) {
        return projectRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Project not found with ID: " + id));
    }
}
```