```java
package com.tasks.taskmanagement.service;

import com.tasks.taskmanagement.dto.TagDTO;
import com.tasks.taskmanagement.entity.Tag;
import com.tasks.taskmanagement.exception.DuplicateResourceException;
import com.tasks.taskmanagement.exception.ResourceNotFoundException;
import com.tasks.taskmanagement.repository.TagRepository;
import com.tasks.taskmanagement.util.MapperUtil;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class TagService {

    private final TagRepository tagRepository;
    private final MapperUtil mapperUtil;

    @Transactional
    @CacheEvict(value = "tags", allEntries = true) // Evict all tags cache on create
    public TagDTO createTag(TagDTO tagDTO) {
        log.info("Creating new tag: {}", tagDTO.getName());
        if (tagRepository.existsByName(tagDTO.getName())) {
            throw new DuplicateResourceException("Tag with name '" + tagDTO.getName() + "' already exists.");
        }

        Tag tag = mapperUtil.map(tagDTO, Tag.class);
        tag.setId(null); // Ensure ID is generated by JPA

        Tag savedTag = tagRepository.save(tag);
        log.info("Tag '{}' created successfully.", savedTag.getName());
        return mapperUtil.map(savedTag, TagDTO.class);
    }

    @Cacheable(value = "tags", key = "#id")
    public TagDTO getTagById(UUID id) {
        log.info("Fetching tag with ID: {}", id);
        Tag tag = tagRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Tag not found with ID: " + id));
        return mapperUtil.map(tag, TagDTO.class);
    }

    @Cacheable(value = "tags", key = "'all'")
    public List<TagDTO> getAllTags() {
        log.info("Fetching all tags.");
        return tagRepository.findAll().stream()
                .map(tag -> mapperUtil.map(tag, TagDTO.class))
                .collect(Collectors.toList());
    }

    @Transactional
    @CacheEvict(value = "tags", allEntries = true) // Evict all tags cache on update
    public TagDTO updateTag(UUID id, TagDTO tagDTO) {
        log.info("Updating tag with ID: {}", id);
        Tag existingTag = tagRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Tag not found with ID: " + id));

        if (!existingTag.getName().equals(tagDTO.getName()) && tagRepository.existsByName(tagDTO.getName())) {
            throw new DuplicateResourceException("Tag with name '" + tagDTO.getName() + "' already exists.");
        }

        existingTag.setName(tagDTO.getName());
        Tag updatedTag = tagRepository.save(existingTag);
        log.info("Tag with ID {} updated successfully to name '{}'.", id, updatedTag.getName());
        return mapperUtil.map(updatedTag, TagDTO.class);
    }

    @Transactional
    @CacheEvict(value = "tags", allEntries = true) // Evict all tags cache on delete
    public void deleteTag(UUID id) {
        log.info("Deleting tag with ID: {}", id);
        if (!tagRepository.existsById(id)) {
            throw new ResourceNotFoundException("Tag not found with ID: " + id);
        }
        tagRepository.deleteById(id);
        log.info("Tag with ID {} deleted successfully.", id);
    }

    // Helper method to retrieve Tag entity
    public Tag getTagEntityById(UUID id) {
        return tagRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Tag not found with ID: " + id));
    }
}
```