```java
package com.tasks.taskmanagement.service;

import com.tasks.taskmanagement.dto.TaskDTO;
import com.tasks.taskmanagement.entity.Project;
import com.tasks.taskmanagement.entity.Tag;
import com.tasks.taskmanagement.entity.Task;
import com.tasks.taskmanagement.entity.Task.Priority;
import com.tasks.taskmanagement.entity.Task.Status;
import com.tasks.taskmanagement.entity.User;
import com.tasks.taskmanagement.exception.ResourceNotFoundException;
import com.tasks.taskmanagement.exception.UnauthorizedException;
import com.tasks.taskmanagement.repository.TaskRepository;
import com.tasks.taskmanagement.util.MapperUtil;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class TaskService {

    private final TaskRepository taskRepository;
    private final UserService userService;
    private final ProjectService projectService;
    private final TagService tagService;
    private final AuthService authService;
    private final MapperUtil mapperUtil;

    @Transactional
    @CacheEvict(value = "tasks", allEntries = true) // Evict all tasks cache on create
    public TaskDTO createTask(TaskDTO taskDTO) {
        log.info("Creating new task: {}", taskDTO.getTitle());
        User currentUser = authService.getCurrentAuthenticatedUser();

        Task task = mapperUtil.map(taskDTO, Task.class);
        task.setId(null); // Ensure ID is generated by JPA

        // Assignee
        if (taskDTO.getAssigneeId() != null) {
            User assignee = userService.getUserEntityById(taskDTO.getAssigneeId());
            task.setAssignee(assignee);
        } else {
            task.setAssignee(currentUser); // Default to current user if not specified
        }

        // Project
        if (taskDTO.getProjectId() != null) {
            Project project = projectService.getProjectEntityById(taskDTO.getProjectId());
            // Authorization check: User must be owner of the project to add tasks to it
            if (!project.getOwner().getId().equals(currentUser.getId()) && currentUser.getRole() != User.Role.ADMIN) {
                throw new UnauthorizedException("You are not authorized to add tasks to this project.");
            }
            task.setProject(project);
        }

        // Tags
        if (taskDTO.getTags() != null && !taskDTO.getTags().isEmpty()) {
            Set<Tag> tags = taskDTO.getTags().stream()
                    .map(tagDTO -> tagService.getTagEntityById(tagDTO.getId()))
                    .collect(Collectors.toSet());
            task.setTags(tags);
        }

        Task savedTask = taskRepository.save(task);
        log.info("Task '{}' created successfully by user '{}'.", savedTask.getTitle(), currentUser.getUsername());
        return mapperUtil.map(savedTask, TaskDTO.class);
    }

    @Cacheable(value = "tasks", key = "#id")
    public TaskDTO getTaskById(UUID id) {
        log.info("Fetching task with ID: {}", id);
        Task task = taskRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Task not found with ID: " + id));

        // Authorization check: user must be assignee, project owner, or admin
        User currentUser = authService.getCurrentAuthenticatedUser();
        boolean isAssignee = task.getAssignee() != null && task.getAssignee().getId().equals(currentUser.getId());
        boolean isProjectOwner = task.getProject() != null && task.getProject().getOwner().getId().equals(currentUser.getId());

        if (!isAssignee && !isProjectOwner && currentUser.getRole() != User.Role.ADMIN) {
            throw new UnauthorizedException("You are not authorized to view this task.");
        }

        return mapperUtil.map(task, TaskDTO.class);
    }

    @Cacheable(value = "tasks", key = "'all'")
    public List<TaskDTO> getAllTasks() {
        log.info("Fetching all tasks (admin only).");
        // Typically, this endpoint would be restricted to ADMIN or heavily filtered for users
        return taskRepository.findAll().stream()
                .map(task -> mapperUtil.map(task, TaskDTO.class))
                .collect(Collectors.toList());
    }

    @Cacheable(value = "tasks", key = "'byUser:' + #userId + ':' + #projectId + ':' + #status")
    public List<TaskDTO> getTasksForUser(UUID userId, UUID projectId, Status status) {
        log.info("Fetching tasks for user ID: {} with project ID: {} and status: {}", userId, projectId, status);
        // Authorization: User can only see their own assigned tasks or tasks in projects they own
        User currentUser = authService.getCurrentAuthenticatedUser();
        if (!currentUser.getId().equals(userId) && currentUser.getRole() != User.Role.ADMIN) {
            throw new UnauthorizedException("You are not authorized to view tasks for another user.");
        }

        List<Task> tasks = taskRepository.findTasksByAssigneeAndFilters(userId, projectId, status);
        return tasks.stream()
                .map(task -> mapperUtil.map(task, TaskDTO.class))
                .collect(Collectors.toList());
    }

    @Transactional
    @CacheEvict(value = "tasks", allEntries = true) // Evict all tasks cache on update
    public TaskDTO updateTask(UUID id, TaskDTO taskDTO) {
        log.info("Updating task with ID: {}", id);
        Task existingTask = taskRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Task not found with ID: " + id));

        // Authorization check: user must be assignee, project owner, or admin to update
        User currentUser = authService.getCurrentAuthenticatedUser();
        boolean isAssignee = existingTask.getAssignee() != null && existingTask.getAssignee().getId().equals(currentUser.getId());
        boolean isProjectOwner = existingTask.getProject() != null && existingTask.getProject().getOwner().getId().equals(currentUser.getId());

        if (!isAssignee && !isProjectOwner && currentUser.getRole() != User.Role.ADMIN) {
            throw new UnauthorizedException("You are not authorized to update this task.");
        }

        existingTask.setTitle(taskDTO.getTitle());
        existingTask.setDescription(taskDTO.getDescription());
        existingTask.setStatus(taskDTO.getStatus());
        existingTask.setPriority(taskDTO.getPriority());
        existingTask.setDueDate(taskDTO.getDueDate());

        // Update Assignee
        if (taskDTO.getAssigneeId() != null && !Objects.equals(taskDTO.getAssigneeId(), existingTask.getAssignee() != null ? existingTask.getAssignee().getId() : null)) {
            User newAssignee = userService.getUserEntityById(taskDTO.getAssigneeId());
            existingTask.setAssignee(newAssignee);
        } else if (taskDTO.getAssigneeId() == null) {
            existingTask.setAssignee(null);
        }

        // Update Project
        if (taskDTO.getProjectId() != null && !Objects.equals(taskDTO.getProjectId(), existingTask.getProject() != null ? existingTask.getProject().getId() : null)) {
            Project newProject = projectService.getProjectEntityById(taskDTO.getProjectId());
            // Additional auth check if project is changed: new project must be owned by current user or admin
            if (!newProject.getOwner().getId().equals(currentUser.getId()) && currentUser.getRole() != User.Role.ADMIN) {
                throw new UnauthorizedException("You are not authorized to assign this task to the specified project.");
            }
            existingTask.setProject(newProject);
        } else if (taskDTO.getProjectId() == null) {
            existingTask.setProject(null);
        }


        // Update Tags
        if (taskDTO.getTags() != null) {
            Set<Tag> newTags = taskDTO.getTags().stream()
                    .map(tagDTO -> tagService.getTagEntityById(tagDTO.getId()))
                    .collect(Collectors.toSet());
            existingTask.setTags(newTags);
        } else {
            existingTask.setTags(new HashSet<>()); // Clear all tags
        }


        Task updatedTask = taskRepository.save(existingTask);
        log.info("Task with ID {} updated successfully.", id);
        return mapperUtil.map(updatedTask, TaskDTO.class);
    }

    @Transactional
    @CacheEvict(value = "tasks", allEntries = true) // Evict all tasks cache on delete
    public void deleteTask(UUID id) {
        log.info("Deleting task with ID: {}", id);
        Task existingTask = taskRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Task not found with ID: " + id));

        // Authorization check: user must be assignee, project owner, or admin to delete
        User currentUser = authService.getCurrentAuthenticatedUser();
        boolean isAssignee = existingTask.getAssignee() != null && existingTask.getAssignee().getId().equals(currentUser.getId());
        boolean isProjectOwner = existingTask.getProject() != null && existingTask.getProject().getOwner().getId().equals(currentUser.getId());

        if (!isAssignee && !isProjectOwner && currentUser.getRole() != User.Role.ADMIN) {
            throw new UnauthorizedException("You are not authorized to delete this task.");
        }

        taskRepository.deleteById(id);
        log.info("Task with ID {} deleted successfully.", id);
    }
}
```