```cpp
#pragma once

#include <drogon/drogon.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/DbClient.h>
#include "../models/User.h"
#include "../utils/Logger.h"
#include "../utils/Common.h" // For ApiException

/**
 * @brief Repository for User data access operations.
 *
 * This class provides methods to perform CRUD operations on the 'users' table.
 * It abstracts the database interaction logic from the business services.
 */
class UserRepository {
public:
    /**
     * @brief Constructs a UserRepository with a database client.
     * @param client The shared pointer to the Drogon DbClient.
     */
    explicit UserRepository(drogon::orm::DbClientPtr client = nullptr);

    /**
     * @brief Finds a user by their ID.
     * @param id The UUID of the user.
     * @return An optional User object if found.
     */
    drogon::Task<std::optional<User>> findById(const UUID& id);

    /**
     * @brief Finds a user by their email address.
     * @param email The email address of the user.
     * @return An optional User object if found.
     */
    drogon::Task<std::optional<User>> findByEmail(const std::string& email);

    /**
     * @brief Finds a user by their username.
     * @param username The username of the user.
     * @return An optional User object if found.
     */
    drogon::Task<std::optional<User>> findByUsername(const std::string& username);

    /**
     * @brief Inserts a new user into the database.
     * @param user The User object to insert (ID might be generated by DB).
     * @return The inserted User object with generated ID and timestamps.
     * @throws Common::ApiException if a database error occurs (e.g., duplicate email/username).
     */
    drogon::Task<User> insert(User user);

    /**
     * @brief Updates an existing user in the database.
     * @param user The User object with updated fields.
     * @return The updated User object.
     * @throws Common::ApiException if the user is not found or a database error occurs.
     */
    drogon::Task<User> update(const User& user);

    /**
     * @brief Deletes a user from the database by ID.
     * @param id The UUID of the user to delete.
     * @return True if the user was deleted, false if not found.
     * @throws Common::ApiException if a database error occurs.
     */
    drogon::Task<bool> remove(const UUID& id);

    /**
     * @brief Retrieves all users with pagination.
     * @param limit The maximum number of users to retrieve.
     * @param offset The number of users to skip.
     * @return A vector of User objects.
     */
    drogon::Task<std::vector<User>> findAll(size_t limit, size_t offset);

private:
    drogon::orm::DbClientPtr dbClient;
};
```