```cpp
#include "UserRepository.h"
#include "../database/DBManager.h"

UserRepository::UserRepository(drogon::orm::DbClientPtr client) {
    if (client) {
        dbClient = client;
    } else {
        dbClient = DBManager::getClient();
    }
}

drogon::Task<std::optional<User>> UserRepository::findById(const UUID& id) {
    try {
        auto result = co_await dbClient->execSqlCoro("SELECT * FROM users WHERE id = $1", id);
        if (result.empty()) {
            co_return std::nullopt;
        }
        co_return User::fromDrogonModel(result[0]);
    } catch (const drogon::orm::DrogonDbException& e) {
        LOG_ERROR("Database error finding user by ID {}: {}", id, e.what());
        throw Common::ApiException(500, "Database error: " + std::string(e.what()));
    }
}

drogon::Task<std::optional<User>> UserRepository::findByEmail(const std::string& email) {
    try {
        auto result = co_await dbClient->execSqlCoro("SELECT * FROM users WHERE email = $1", email);
        if (result.empty()) {
            co_return std::nullopt;
        }
        co_return User::fromDrogonModel(result[0]);
    } catch (const drogon::orm::DrogonDbException& e) {
        LOG_ERROR("Database error finding user by email {}: {}", email, e.what());
        throw Common::ApiException(500, "Database error: " + std::string(e.what()));
    }
}

drogon::Task<std::optional<User>> UserRepository::findByUsername(const std::string& username) {
    try {
        auto result = co_await dbClient->execSqlCoro("SELECT * FROM users WHERE username = $1", username);
        if (result.empty()) {
            co_return std::nullopt;
        }
        co_return User::fromDrogonModel(result[0]);
    } catch (const drogon::orm::DrogonDbException& e) {
        LOG_ERROR("Database error finding user by username {}: {}", username, e.what());
        throw Common::ApiException(500, "Database error: " + std::string(e.what()));
    }
}

drogon::Task<User> UserRepository::insert(User user) {
    try {
        // ID is generated by DB (uuid_generate_v4())
        auto result = co_await dbClient->execSqlCoro(
            "INSERT INTO users (username, email, password_hash) VALUES ($1, $2, $3) RETURNING *",
            user.username, user.email, user.password_hash
        );
        if (result.empty()) {
            LOG_ERROR("Insert user returned no data. User: {}", user.email);
            throw Common::ApiException(500, "Failed to retrieve user after insertion.");
        }
        co_return User::fromDrogonModel(result[0]);
    } catch (const drogon::orm::DrogonDbException& e) {
        LOG_ERROR("Database error inserting user {}: {}", user.email, e.what());
        if (std::string(e.what()).find("duplicate key value violates unique constraint") != std::string::npos) {
            throw Common::ApiException(409, "A user with this email or username already exists.");
        }
        throw Common::ApiException(500, "Database error: " + std::string(e.what()));
    }
}

drogon::Task<User> UserRepository::update(const User& user) {
    try {
        auto result = co_await dbClient->execSqlCoro(
            "UPDATE users SET username = $1, email = $2, password_hash = $3 WHERE id = $4 RETURNING *",
            user.username, user.email, user.password_hash, user.id
        );
        if (result.empty()) {
            LOG_WARN("User with ID {} not found for update.", user.id);
            throw Common::ApiException(404, "User not found.");
        }
        co_return User::fromDrogonModel(result[0]);
    } catch (const drogon::orm::DrogonDbException& e) {
        LOG_ERROR("Database error updating user {}: {}", user.id, e.what());
        if (std::string(e.what()).find("duplicate key value violates unique constraint") != std::string::npos) {
            throw Common::ApiException(409, "Another user with this email or username already exists.");
        }
        throw Common::ApiException(500, "Database error: " + std::string(e.what()));
    }
}

drogon::Task<bool> UserRepository::remove(const UUID& id) {
    try {
        auto result = co_await dbClient->execSqlCoro("DELETE FROM users WHERE id = $1 RETURNING id", id);
        co_return !result.empty();
    } catch (const drogon::orm::DrogonDbException& e) {
        LOG_ERROR("Database error deleting user {}: {}", id, e.what());
        throw Common::ApiException(500, "Database error: " + std::string(e.what()));
    }
}

drogon::Task<std::vector<User>> UserRepository::findAll(size_t limit, size_t offset) {
    try {
        auto result = co_await dbClient->execSqlCoro(
            "SELECT * FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2",
            limit, offset
        );
        std::vector<User> users;
        for (const auto& row : result) {
            users.push_back(User::fromDrogonModel(row));
        }
        co_return users;
    } catch (const drogon::orm::DrogonDbException& e) {
        LOG_ERROR("Database error retrieving all users: {}", e.what());
        throw Common::ApiException(500, "Database error: " + std::string(e.what()));
    }
}
```