```javascript
import React, { useEffect, useState } from 'react';
import { getMediaItems, createMedia, updateMedia, deleteMedia } from '../api/media';
import { useAuth } from '../contexts/AuthContext';
import Button from '../components/Button';
import Input from '../components/Input';
import Spinner from '../components/Spinner';
import Modal from '../components/Modal';
import { toast } from 'react-toastify';
import { PlusIcon, PencilIcon, TrashIcon, CloudArrowUpIcon, LinkIcon } from '@heroicons/react/24/outline';

const MediaLibrary = () => {
  const [mediaItems, setMediaItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [currentMedia, setCurrentMedia] = useState(null); // For editing
  const [deletingId, setDeletingId] = useState(null);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const { userRole } = useAuth();
  const canManageMedia = userRole === 'admin' || userRole === 'editor';

  const [uploadForm, setUploadForm] = useState({
    name: '',
    filename: '', // This would typically be generated by the server post-upload
    path: '', // This would be the URL to the uploaded file
    mimeType: '',
    size: 0,
  });

  useEffect(() => {
    fetchMediaItems();
  }, []);

  const fetchMediaItems = async () => {
    setLoading(true);
    try {
      const { results } = await getMediaItems();
      setMediaItems(results);
    } catch (error) {
      toast.error('Failed to fetch media items.');
      console.error('Error fetching media:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleUploadChange = (e) => {
    setUploadForm((prev) => ({ ...prev, [e.target.id]: e.target.value }));
  };

  const handleCreateMedia = async (e) => {
    e.preventDefault();
    setSubmitting(true);
    try {
      // Basic client-side validation for simplified demo
      if (!uploadForm.name || !uploadForm.filename || !uploadForm.path || !uploadForm.mimeType || uploadForm.size <= 0) {
        toast.error('Please fill all required fields for media upload.');
        return;
      }
      await createMedia(uploadForm);
      toast.success('Media item created successfully!');
      setShowUploadModal(false);
      setUploadForm({ name: '', filename: '', path: '', mimeType: '', size: 0 });
      fetchMediaItems();
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to create media item.');
      console.error('Error creating media:', error);
    } finally {
      setSubmitting(false);
    }
  };

  const handleEditClick = (media) => {
    setCurrentMedia({ ...media });
    setShowEditModal(true);
  };

  const handleEditChange = (e) => {
    setCurrentMedia((prev) => ({ ...prev, [e.target.id]: e.target.value }));
  };

  const handleUpdateMedia = async (e) => {
    e.preventDefault();
    setSubmitting(true);
    try {
      await updateMedia(currentMedia.id, currentMedia);
      toast.success('Media item updated successfully!');
      setShowEditModal(false);
      setCurrentMedia(null);
      fetchMediaItems();
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to update media item.');
      console.error('Error updating media:', error);
    } finally {
      setSubmitting(false);
    }
  };

  const handleDeleteClick = (id) => {
    setDeletingId(id);
    setShowDeleteModal(true);
  };

  const confirmDelete = async () => {
    if (!deletingId) return;

    try {
      await deleteMedia(deletingId);
      toast.success('Media item deleted successfully!');
      fetchMediaItems();
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to delete media item.');
      console.error('Error deleting media:', error);
    } finally {
      setDeletingId(null);
      setShowDeleteModal(false);
    }
  };

  if (loading) {
    return <div className="flex justify-center items-center h-64"><Spinner /></div>;
  }

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold text-gray-900">Media Library</h1>
        {canManageMedia && (
          <Button onClick={() => setShowUploadModal(true)} className="flex items-center">
            <CloudArrowUpIcon className="h-5 w-5 mr-2" /> Upload Media
          </Button>
        )}
      </div>

      {mediaItems.length === 0 ? (
        <p className="text-gray-600">No media items uploaded yet.</p>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          {mediaItems.map((media) => (
            <div key={media.id} className="bg-white rounded-lg shadow-md overflow-hidden">
              <div className="relative h-48 w-full bg-gray-200 flex items-center justify-center">
                {media.mimeType.startsWith('image/') ? (
                  <img src={media.path} alt={media.name} className="object-cover w-full h-full" />
                ) : (
                  <DocumentTextIcon className="h-24 w-24 text-gray-400" />
                )}
                <a href={media.path} target="_blank" rel="noopener noreferrer" className="absolute top-2 right-2 text-white bg-black bg-opacity-50 rounded-full p-1 hover:bg-opacity-75">
                  <LinkIcon className="h-5 w-5" />
                </a>
              </div>
              <div className="p-4">
                <h3 className="text-lg font-semibold text-gray-900 truncate">{media.name}</h3>
                <p className="text-sm text-gray-600">Type: {media.mimeType}</p>
                <p className="text-sm text-gray-600">Size: {(media.size / 1024 / 1024).toFixed(2)} MB</p>
                <div className="flex justify-end space-x-2 mt-4">
                  <Button variant="secondary" size="sm" onClick={() => handleEditClick(media)} disabled={!canManageMedia}>
                    <PencilIcon className="h-4 w-4" />
                  </Button>
                  <Button variant="danger" size="sm" onClick={() => handleDeleteClick(media.id)} disabled={!canManageMedia}>
                    <TrashIcon className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Upload Media Modal */}
      <Modal
        show={showUploadModal}
        onClose={() => setShowUploadModal(false)}
        title="Upload New Media"
        footer={
          <>
            <Button variant="secondary" onClick={() => setShowUploadModal(false)} className="mr-2">
              Cancel
            </Button>
            <Button type="submit" onClick={handleCreateMedia} loading={submitting}>
              Upload
            </Button>
          </>
        }
      >
        <form onSubmit={handleCreateMedia} className="space-y-4">
          <Input label="Name" id="name" value={uploadForm.name} onChange={handleUploadChange} required />
          <Input label="Filename (e.g., image.jpg)" id="filename" value={uploadForm.filename} onChange={handleUploadChange} required />
          <Input label="Public Path/URL" id="path" value={uploadForm.path} onChange={handleUploadChange} required />
          <Input label="MIME Type (e.g., image/jpeg)" id="mimeType" value={uploadForm.mimeType} onChange={handleUploadChange} required />
          <Input label="Size (bytes)" id="size" type="number" value={uploadForm.size} onChange={handleUploadChange} required />
          <p className="text-sm text-gray-500">
            Note: In a production environment, file uploads would involve a dedicated upload input and server-side processing to generate the filename, path, mimeType, and size. This form simulates that process.
          </p>
        </form>
      </Modal>

      {/* Edit Media Modal */}
      {currentMedia && (
        <Modal
          show={showEditModal}
          onClose={() => setShowEditModal(false)}
          title={`Edit Media: ${currentMedia.name}`}
          footer={
            <>
              <Button variant="secondary" onClick={() => setShowEditModal(false)} className="mr-2">
                Cancel
              </Button>
              <Button type="submit" onClick={handleUpdateMedia} loading={submitting}>
                Save Changes
              </Button>
            </>
          }
        >
          <form onSubmit={handleUpdateMedia} className="space-y-4">
            <Input label="Name" id="name" value={currentMedia.name} onChange={handleEditChange} required />
            <Input label="Public Path/URL" id="path" value={currentMedia.path} onChange={handleEditChange} required />
            <Input label="MIME Type" id="mimeType" value={currentMedia.mimeType} onChange={handleEditChange} required />
            <Input label="Size (bytes)" id="size" type="number" value={currentMedia.size} onChange={handleEditChange} required />
          </form>
        </Modal>
      )}

      {/* Delete Media Modal */}
      <Modal
        show={showDeleteModal}
        onClose={() => setShowDeleteModal(false)}
        title="Delete Media Item"
        footer={
          <>
            <Button variant="secondary" onClick={() => setShowDeleteModal(false)} className="mr-2">
              Cancel
            </Button>
            <Button variant="danger" onClick={confirmDelete} loading={deletingId && !showDeleteModal ? true : false}>
              Delete
            </Button>
          </>
        }
      >
        <p className="text-gray-700">Are you sure you want to delete this media item? This action cannot be undone.</p>
      </Modal>
    </div>
  );
};

export default MediaLibrary;
```