-- Seed data for CMS

-- Insert an admin user (password 'adminpassword' - hashed using bcrypt, actual hash would be generated by PasswordHasher)
-- For demonstration, we'll use a pre-hashed password. In real application, register via API.
-- Hashed 'adminpassword' using bcrypt (cost 10) for example: $2a$10$vN0w.u5r4Wj/W1sX.2M.4O.f5.l.R3Z.G7h.B.X8
-- It's important to use the actual hasher for consistency.
-- Let's use a known hash for 'password123' for easier testing in local dev
-- For 'password123': $2a$10$0k4D1XyGg7hN5M7K8L9O.q/J/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S/T/U/V/W/X/Y/Z
-- (This is just an example hash, a real hash would be generated dynamically)
INSERT INTO users (id, username, email, password_hash, role) VALUES
    ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'admin', 'admin@example.com', '$2a$10$p0VbT9Xp1B.w.m.Z0Y.7I.b/v4k.N5E6F7G8H9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z', 'admin')
ON CONFLICT (username) DO NOTHING;

-- Insert a regular user
INSERT INTO users (id, username, email, password_hash, role) VALUES
    ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'johndoe', 'john.doe@example.com', '$2a$10$p0VbT9Xp1B.w.m.Z0Y.7I.b/v4k.N5E6F7G8H9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z', 'user')
ON CONFLICT (username) DO NOTHING;

-- Insert some sample content
INSERT INTO content (title, slug, body, author_id, status, published_at) VALUES
    ('Welcome to CMS', 'welcome-to-cms', 'This is the first article published on our new C++ CMS.', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'published', NOW()),
    ('Getting Started Guide', 'getting-started-guide', 'Learn how to use your new CMS effectively with this comprehensive guide.', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'published', NOW()),
    ('Draft Article Ideas', 'draft-article-ideas', 'A collection of ideas for future articles, currently in draft status.', 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'draft', NULL)
ON CONFLICT (slug) DO NOTHING;