```cpp
#include "app.h"
#include <iostream>

OptiDBApp::OptiDBApp() {
    Logger::init(static_cast<LogLevel>(spdlog::level::from_string(config.log_level)), DEFAULT_LOG_FILE);
    LOG_INFO("OptiDB application initializing...");
    setup_dependencies();
    setup_middleware();
    setup_routes();
    LOG_INFO("OptiDB application initialized.");
}

void OptiDBApp::setup_dependencies() {
    db_connection = std::make_shared<PostgresConnection>(config);
    
    // JWT Manager
    std::shared_ptr<JWTManager> jwt_manager = std::make_shared<JWTManager>(config);

    // Services
    auth_service = std::make_shared<AuthService>(db_connection, jwt_manager);
    target_db_service = std::make_shared<TargetDbService>(db_connection, config);
    optimization_engine = std::make_shared<OptimizationEngine>(db_connection, target_db_service);

    // Middleware instances
    error_middleware = std::make_shared<middleware::ErrorMiddleware>();
    logging_middleware = std::make_shared<middleware::LoggingMiddleware>();
    auth_middleware = std::make_shared<middleware::AuthMiddleware>(jwt_manager);

    // Controllers
    auth_controller = std::make_shared<AuthController>(app, auth_service);
    target_db_controller = std::make_shared<TargetDbController>(app, target_db_service, optimization_engine);
}

void OptiDBApp::setup_middleware() {
    // Order matters: Logging -> Auth -> Error (Error handles responses potentially generated by others)
    app.add_middleware<middleware::LoggingMiddleware>(*logging_middleware);
    app.add_middleware<middleware::AuthMiddleware>(*auth_middleware);
    // Error middleware should be last to catch exceptions from handlers/other middleware
    app.add_middleware<middleware::ErrorMiddleware>(*error_middleware);
}

void OptiDBApp::setup_routes() {
    // Routes are handled by controllers
    // Controllers register their routes directly with the app instance.
    // e.g., auth_controller->setup_routes(app); implicitly done in constructor.
}

void OptiDBApp::run() {
    LOG_INFO("OptiDB server starting on port {}.", config.server_port);
    app.port(config.server_port).multithreaded().run();
    LOG_INFO("OptiDB server stopped.");
}
```