```ini
[alembic]
script_location = backend/migrations
prepend_sys_path = .
version_locations = %(script_location)s/versions
file_template = %%(rev)s_%%(year)s%%(month).02d%%(day).02d_%%(hour).02d%%(minute).02d_%%(slug)s
sqlalchemy.url = %(DATABASE_URL)s

[post_write_hooks]
```