```sql
-- Insert default roles
INSERT INTO roles (authority) VALUES ('USER') ON CONFLICT (authority) DO NOTHING;
INSERT INTO roles (authority) VALUES ('ADMIN') ON CONFLICT (authority) DO NOTHING;

-- Insert a default admin user (password 'adminpass')
-- Use BCrypt encoded password (e.g., generated by https://www.bcrypt-generator.com/)
-- The password 'adminpass' encrypted with BCrypt is $2a$10$w09u7uR7eF3B5qB8o3d31O.1K9vB.k9XqX/9XqX/9XqX.x0F.y0F.y0F.y0F
-- You should replace this with a freshly generated one or use environment variables for passwords.
INSERT INTO users (email, password, first_name, last_name, created_at, updated_at) VALUES
('admin@example.com', '$2a$10$w09u7uR7eF3B5qB8o3d31O.1K9vB.k9XqX/9XqX/9XqX.x0F.y0F.y0F.y0F', 'Admin', 'User', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, password = EXCLUDED.password, updated_at = EXCLUDED.updated_at;

-- Assign ADMIN role to the admin user
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r
WHERE u.email = 'admin@example.com' AND r.authority = 'ADMIN'
ON CONFLICT (user_id, role_id) DO NOTHING;

-- Assign USER role to the admin user (optional, if admin should also have user privileges)
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r
WHERE u.email = 'admin@example.com' AND r.authority = 'USER'
ON CONFLICT (user_id, role_id) DO NOTHING;


-- Insert a default regular user (password 'userpass')
INSERT INTO users (email, password, first_name, last_name, created_at, updated_at) VALUES
('user@example.com', '$2a$10$Q7c.s2L7t0D4c2Z9q3t9gO.1K9vB.k9XqX/9XqX/9XqX.x0F.y0F.y0F.y0F', 'Regular', 'User', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (email) DO UPDATE SET first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, password = EXCLUDED.password, updated_at = EXCLUDED.updated_at;

-- Assign USER role to the regular user
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r
WHERE u.email = 'user@example.com' AND r.authority = 'USER'
ON CONFLICT (user_id, role_id) DO NOTHING;

-- Example tasks for the regular user
INSERT INTO tasks (title, description, completed, user_id, created_at, updated_at)
SELECT 'Complete project proposal', 'Draft the initial proposal for the new authentication system project.', FALSE, u.id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM users u WHERE u.email = 'user@example.com'
ON CONFLICT DO NOTHING; -- Add a unique constraint on title+user_id if you want to prevent duplicates for example

INSERT INTO tasks (title, description, completed, user_id, created_at, updated_at)
SELECT 'Review code for sprint 1', 'Perform peer code review for backend authentication module.', FALSE, u.id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM users u WHERE u.email = 'user@example.com'
ON CONFLICT DO NOTHING;

INSERT INTO tasks (title, description, completed, user_id, created_at, updated_at)
SELECT 'Set up CI/CD pipeline', 'Configure GitHub Actions for automated build and tests.', TRUE, u.id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM users u WHERE u.email = 'user@example.com'
ON CONFLICT DO NOTHING;

-- Example tasks for the admin user
INSERT INTO tasks (title, description, completed, user_id, created_at, updated_at)
SELECT 'Monitor production servers', 'Check logs and performance metrics for all deployed services.', FALSE, u.id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM users u WHERE u.email = 'admin@example.com'
ON CONFLICT DO NOTHING;

INSERT INTO tasks (title, description, completed, user_id, created_at, updated_at)
SELECT 'Approve vacation requests', 'Review and approve pending vacation requests from team members.', TRUE, u.id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM users u WHERE u.email = 'admin@example.com'
ON CONFLICT DO NOTHING;
```