```
[alembic]
script_location = alembic
sqlalchemy.url = ${DATABASE_URL}
revision_path = alembic/versions
version_locations = %(script_location)s/versions

# A custom template for new migrations
# template =

# set to 'true' to run the environment during
# the 'list_templates' command
# environment_run = false

[post_write_hooks]
# post_write_hooks = success:black, failure:print_message

# [black]
# type = console_scripts
# entrypoint = black
# options = %(file)s
```