```ini
[alembic]
script_location = alembic
sqlalchemy.url = postgresql+psycopg2://user:password@db:5432/payment_processor # Will be overwritten by env_py
file_template = %%(year)d%%(month).2d%%(day).2d%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

[post_write_hooks]
```