```cpp
#pragma once

#include "src/models/UserBase.h" // Generated by drogon_ctl

namespace ApexContent::Model {

class User : public UserBase {
public:
    using UserBase::UserBase; // Inherit constructors
    // Add custom business logic or methods here
    
    // For example, a method to get user roles
    std::future<std::vector<std::string>> getRoles(const drogon::orm::DbClientPtr& dbClient) const;
};

} // namespace ApexContent::Model
```