```ini
[alembic]
script_location = alembic
sqlalchemy.url = ${DATABASE_URL}
revision_table_filename = alembic_version.py

# logging configuration
file_template = %%(year)s%%(month).02d%%(day).02d_%%(rev)s_%%(slug)s

[loggers]
alembic = INFO
sqlalchemy = INFO
root = INFO

[handlers]
console =
    class=logging.StreamHandler
    formatter=generic

[formatters]
generic =
    format=%(levelname)-5s [%(name)s] %(message)s
    datefmt=%H:%M:%S
```