```javascript
import http from 'k6/http';
import { check, sleep } from 'k6';
import { SharedArray } from 'k6/data';

// --- Configuration ---
export const options = {
    vus: 10,      // Number of virtual users
    duration: '30s', // Duration of the test
    thresholds: {
        http_req_duration: ['p(95)<500'], // 95% of requests must complete within 500ms
        http_req_failed: ['rate<0.01'],   // Error rate should be less than 1%
    },
};

// Base URL for the backend
const BASE_URL = 'http://localhost:5000/api';

// Shared data for more realistic requests (e.g., specific post IDs, categories)
// This data will be loaded once and shared across all VUs
const posts = new SharedArray('published_posts', function () {
    // In a real scenario, you'd fetch this from a setup script or a live API.
    // For now, let's assume we have some known post IDs.
    return [
        { id: '1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d', slug: 'getting-started-nodejs-express' },
        { id: '1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6e', slug: 'benefits-healthy-diet' },
        // ... add more as needed from your seed data or actual API
    ];
});


// --- Main Test Scenario ---
export default function () {
    // 1. Get all published posts (cached endpoint)
    let res = http.get(`${BASE_URL}/posts/published`);
    check(res, {
        'GET /posts/published status is 200': (r) => r.status === 200,
        'GET /posts/published response has data': (r) => r.json() && r.json().length > 0,
    });
    sleep(1);

    // 2. Get a random published post by slug (cached endpoint)
    if (posts.length > 0) {
        const randomPost = posts[Math.floor(Math.random() * posts.length)];
        res = http.get(`${BASE_URL}/posts/${randomPost.slug}`);
        check(res, {
            `GET /posts/${randomPost.slug} status is 200`: (r) => r.status === 200,
            'GET /posts/:slug response has title': (r) => r.json() && r.json().title,
        });
    }
    sleep(1);

    // 3. Authenticate (login) - not cached, hits database
    // For proper load testing, you'd pre-create multiple user credentials.
    // For simplicity, using a single user for demonstration.
    const loginPayload = JSON.stringify({
        email: 'admin@example.com',
        password: 'adminpassword',
    });
    const loginHeaders = {
        'Content-Type': 'application/json',
    };
    res = http.post(`${BASE_URL}/auth/login`, loginPayload, { headers: loginHeaders });
    check(res, {
        'POST /auth/login status is 200': (r) => r.status === 200,
        'POST /auth/login has token': (r) => r.json() && r.json().token !== '',
    });
    const authToken = res.json() ? res.json().token : '';
    sleep(1);

    // 4. Get all posts (authenticated endpoint, might be less cached or no cache)
    if (authToken) {
        const authHeaders = {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${authToken}`,
        };
        res = http.get(`${BASE_URL}/posts`, { headers: authHeaders });
        check(res, {
            'GET /posts (authenticated) status is 200': (r) => r.status === 200,
            'GET /posts (authenticated) response has data': (r) => r.json() && r.json().length > 0,
        });
    }
    sleep(1);

    // 5. Simulate creating a post (write operation)
    if (authToken) {
        const createPostPayload = JSON.stringify({
            title: `Load Test Post ${__VU}-${__ITER}`,
            content: 'Content generated by load test.',
            status: 'draft',
            categoryId: 'some-valid-category-id', // Replace with an actual category ID from your DB
        });
        const authHeaders = {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${authToken}`,
        };
        res = http.post(`${BASE_URL}/posts`, createPostPayload, { headers: authHeaders });
        check(res, {
            'POST /posts status is 201': (r) => r.status === 201,
        });
    }
    sleep(1);
}
```