```javascript
const authService = require('../../services/authService');
const db = require('../../db');
const AppError = require('../../utils/appError');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const config = require('../../config/config');
const { setupTestDB, insertUsers, regularUser, adminUser } = require('../fixtures/db.fixture');

describe('Auth Service Unit Tests', () => {
  beforeAll(async () => {
    // Override DB config for tests
    db.sequelize.options.database = 'ml_utilities_test_db';
    await setupTestDB();
  });

  beforeEach(async () => {
    // Clear tables before each test
    await db.User.destroy({ truncate: true, cascade: true });
  });

  afterAll(async () => {
    await db.sequelize.close();
  });

  describe('registerUser', () => {
    test('should register a new user successfully', async () => {
      const userData = { ...regularUser };
      delete userData.id; // ID is generated by DB
      const { user, token } = await authService.registerUser(userData);

      expect(user).toBeDefined();
      expect(user.username).toBe(userData.username);
      expect(user.email).toBe(userData.email);
      expect(user.role).toBe('user'); // Default role
      expect(token).toBeDefined();

      const decoded = jwt.verify(token, config.jwt.secret);
      expect(decoded.id).toBe(user.id);

      const foundUser = await db.User.findByPk(user.id);
      expect(foundUser).not.toBeNull();
      expect(await bcrypt.compare(userData.password, foundUser.password)).toBe(true);
    });

    test('should not register user with duplicate email', async () => {
      await insertUsers([regularUser]);
      const duplicateUserData = { ...regularUser, username: 'anotheruser' }; // Keep email same

      await expect(authService.registerUser(duplicateUserData)).rejects.toThrow(AppError);
      await expect(authService.registerUser(duplicateUserData)).rejects.toHaveProperty('statusCode', 400);
    });

    test('should not register user with duplicate username', async () => {
      await insertUsers([regularUser]);
      const duplicateUserData = { ...regularUser, email: 'another@test.com' }; // Keep username same

      await expect(authService.registerUser(duplicateUserData)).rejects.toThrow(AppError);
      await expect(authService.registerUser(duplicateUserData)).rejects.toHaveProperty('statusCode', 400);
    });
  });

  describe('loginUser', () => {
    test('should log in a user successfully', async () => {
      await insertUsers([regularUser]);
      const { user, token } = await authService.loginUser({
        email: regularUser.email,
        password: regularUser.password,
      });

      expect(user).toBeDefined();
      expect(user.email).toBe(regularUser.email);
      expect(token).toBeDefined();

      const decoded = jwt.verify(token, config.jwt.secret);
      expect(decoded.id).toBe(user.id);
    });

    test('should throw error for incorrect email', async () => {
      await insertUsers([regularUser]);
      await expect(
        authService.loginUser({ email: 'wrong@test.com', password: regularUser.password })
      ).rejects.toThrow(AppError);
      await expect(
        authService.loginUser({ email: 'wrong@test.com', password: regularUser.password })
      ).rejects.toHaveProperty('statusCode', 401);
    });

    test('should throw error for incorrect password', async () => {
      await insertUsers([regularUser]);
      await expect(
        authService.loginUser({ email: regularUser.email, password: 'wrongpassword' })
      ).rejects.toThrow(AppError);
      await expect(
        authService.loginUser({ email: regularUser.email, password: 'wrongpassword' })
      ).rejects.toHaveProperty('statusCode', 401);
    });
  });

  describe('signToken', () => {
    test('should return a valid JWT token', () => {
      const token = authService.signToken(regularUser.id);
      expect(token).toBeDefined();
      const decoded = jwt.verify(token, config.jwt.secret);
      expect(decoded.id).toBe(regularUser.id);
      expect(decoded.exp).toBeDefined();
    });
  });
});
```