[alembic]
# path to migration scripts
script_location = alembic
# template used to generate new revision files
revision_script_template = %(script_location)s/script.py.mako
# template used to generate alembic.ini
file_template = %%(here)s/alembic.ini
# environment that defines the base module for the app.database.models import
# (used by `alembic revision --autogenerate`)
# Make sure to point to your `app.database.models`
sqlalchemy.url = postgresql+asyncpg://horizon_user:horizon_password@db:5432/horizon_db

# logging configuration
[loggers]
keys = root, alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S