import { Test, TestingModule } from '@nestjs/testing';
import { getRepositoryToken } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { UsersService } from '../../src/users/users.service';
import { User } from '../../src/users/user.entity';
import { NotFoundException } from '@nestjs/common';
import { WinstonLogger } from '../../src/common/logger/winston.logger';
import { ConfigService } from '@nestjs/config';

describe('UsersService (Unit)', () => {
  let service: UsersService;
  let userRepository: Repository<User>;
  let logger: WinstonLogger;

  // Mock data
  const mockUser: User = {
    id: 'user-id-1',
    username: 'testuser',
    email: 'test@example.com',
    password: 'hashedpassword',
    avatar: 'avatar.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    roomMembers: [],
    messages: [],
    createdRooms: [],
  };

  const mockUserRepository = {
    create: jest.fn().mockImplementation((dto) => dto),
    save: jest.fn().mockImplementation((user) => ({ ...mockUser, ...user })),
    find: jest.fn().mockResolvedValue([mockUser]),
    findOne: jest.fn().mockResolvedValue(mockUser),
    delete: jest.fn().mockResolvedValue({ affected: 1 }),
  };

  const mockLogger = {
    log: jest.fn(),
    error: jest.fn(),
    warn: jest.fn(),
    debug: jest.fn(),
    verbose: jest.fn(),
    setContext: jest.fn(),
  };

  const mockConfigService = {
    get: jest.fn((key: string) => {
      if (key === 'LOG_LEVEL') return 'debug';
      return null;
    }),
  };

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        UsersService,
        {
          provide: getRepositoryToken(User),
          useValue: mockUserRepository,
        },
        {
          provide: WinstonLogger,
          useValue: mockLogger,
        },
        {
          provide: ConfigService,
          useValue: mockConfigService,
        },
      ],
    }).compile();

    service = module.get<UsersService>(UsersService);
    userRepository = module.get<Repository<User>>(getRepositoryToken(User));
    logger = module.get<WinstonLogger>(WinstonLogger);
  });

  afterEach(() => {
    jest.clearAllMocks(); // Clear mocks after each test
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  describe('create', () => {
    it('should create a user', async () => {
      const createUserDto = {
        username: 'newUser',
        email: 'new@example.com',
        password: 'newhashedpassword',
      };
      const expectedUser = {
        id: expect.any(String), // ID generated by DB
        ...createUserDto,
        avatar: 'avatar.png',
        createdAt: expect.any(Date),
        updatedAt: expect.any(Date),
        roomMembers: [],
        messages: [],
        createdRooms: [],
      };
      mockUserRepository.create.mockReturnValueOnce(expectedUser);
      mockUserRepository.save.mockResolvedValueOnce(expectedUser);


      const result = await service.create(createUserDto);

      expect(userRepository.create).toHaveBeenCalledWith(createUserDto);
      expect(userRepository.save).toHaveBeenCalledWith(expectedUser);
      expect(result).toEqual(expectedUser);
      expect(logger.log).toHaveBeenCalledWith(`Creating new user: ${createUserDto.username}`);
    });
  });

  describe('findAll', () => {
    it('should return an array of users', async () => {
      const result = await service.findAll();
      expect(userRepository.find).toHaveBeenCalled();
      expect(result).toEqual([mockUser]);
      expect(logger.log).toHaveBeenCalledWith('Fetching all users');
    });
  });

  describe('findById', () => {
    it('should find a user by ID', async () => {
      const result = await service.findById(mockUser.id);
      expect(userRepository.findOne).toHaveBeenCalledWith({ where: { id: mockUser.id } });
      expect(result).toEqual(mockUser);
      expect(logger.log).toHaveBeenCalledWith(`Fetching user by ID: ${mockUser.id}`);
    });

    it('should throw NotFoundException if user not found by ID', async () => {
      mockUserRepository.findOne.mockResolvedValueOnce(null);
      await expect(service.findById('non-existent-id')).rejects.toThrow(NotFoundException);
      expect(logger.warn).toHaveBeenCalledWith(`User with ID non-existent-id not found.`);
    });
  });

  describe('findByUsername', () => {
    it('should find a user by username', async () => {
      const result = await service.findByUsername(mockUser.username);
      expect(userRepository.findOne).toHaveBeenCalledWith({ where: { username: mockUser.username } });
      expect(result).toEqual(mockUser);
      expect(logger.log).toHaveBeenCalledWith(`Fetching user by username: ${mockUser.username}`);
    });

    it('should return null if user not found by username', async () => {
      mockUserRepository.findOne.mockResolvedValueOnce(null);
      const result = await service.findByUsername('nonexistent');
      expect(result).toBeNull();
    });
  });

  describe('update', () => {
    it('should update a user', async () => {
      const updateUserDto = { username: 'updatedUser' };
      const updatedUser = { ...mockUser, ...updateUserDto };
      mockUserRepository.findOne.mockResolvedValueOnce(mockUser); // findById call
      mockUserRepository.save.mockResolvedValueOnce(updatedUser);

      const result = await service.update(mockUser.id, updateUserDto);

      expect(userRepository.findOne).toHaveBeenCalledWith({ where: { id: mockUser.id } });
      expect(userRepository.save).toHaveBeenCalledWith(expect.objectContaining(updateUserDto));
      expect(result).toEqual(updatedUser);
      expect(logger.log).toHaveBeenCalledWith(`Updating user with ID: ${mockUser.id}`);
    });

    it('should throw NotFoundException if user to update is not found', async () => {
      mockUserRepository.findOne.mockResolvedValueOnce(null); // findById call fails
      await expect(service.update('non-existent-id', { username: 'x' })).rejects.toThrow(NotFoundException);
    });
  });

  describe('remove', () => {
    it('should remove a user', async () => {
      const result = await service.remove(mockUser.id);
      expect(userRepository.delete).toHaveBeenCalledWith(mockUser.id);
      expect(result).toBe(true);
      expect(logger.log).toHaveBeenCalledWith(`Attempting to remove user with ID: ${mockUser.id}`);
      expect(logger.log).toHaveBeenCalledWith(`User with ID ${mockUser.id} successfully removed.`);
    });

    it('should throw NotFoundException if user to remove is not found', async () => {
      mockUserRepository.delete.mockResolvedValueOnce({ affected: 0 });
      await expect(service.remove('non-existent-id')).rejects.toThrow(NotFoundException);
      expect(logger.warn).toHaveBeenCalledWith(`Deletion failed: User with ID non-existent-id not found.`);
    });
  });
});